version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        BUILD_ENV: development
    ports:
      - "8080:8080"
    environment:
      - DEPLOYMENT_MODE=local
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=go_rbac_db
      - DB_SSLMODE=disable
      - SERVER_PORT=8080
      - SERVER_MODE=debug
    depends_on:
      - postgres
    volumes:
      - ./migrations:/app/migrations:ro
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=go_rbac_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped

volumes:
  postgres_data: 