// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

// API keys for programmatic access
type ApiKey struct {
	ID         uuid.UUID    `json:"id"`
	UserID     uuid.UUID    `json:"user_id"`
	Name       string       `json:"name"`
	KeyHash    string       `json:"key_hash"`
	IsActive   sql.NullBool `json:"is_active"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}

// Dynamic collections that can be created by users
type Collection struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	DisplayName sql.NullString `json:"display_name"`
	Description sql.NullString `json:"description"`
	Icon        sql.NullString `json:"icon"`
	IsSystem    sql.NullBool   `json:"is_system"`
	TenantID    uuid.NullUUID  `json:"tenant_id"`
	CreatedBy   uuid.NullUUID  `json:"created_by"`
	UpdatedBy   uuid.NullUUID  `json:"updated_by"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Customer struct {
	ID        uuid.UUID      `json:"id"`
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	Email     string         `json:"email"`
	Phone     sql.NullString `json:"phone"`
	Address   sql.NullString `json:"address"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

// Field definitions for dynamic collections
type Field struct {
	ID              uuid.UUID             `json:"id"`
	CollectionID    uuid.NullUUID         `json:"collection_id"`
	Name            string                `json:"name"`
	DisplayName     sql.NullString        `json:"display_name"`
	Type            string                `json:"type"`
	IsPrimary       sql.NullBool          `json:"is_primary"`
	IsRequired      sql.NullBool          `json:"is_required"`
	IsUnique        sql.NullBool          `json:"is_unique"`
	DefaultValue    sql.NullString        `json:"default_value"`
	ValidationRules pqtype.NullRawMessage `json:"validation_rules"`
	SortOrder       sql.NullInt32         `json:"sort_order"`
	RelationConfig  pqtype.NullRawMessage `json:"relation_config"`
	TenantID        uuid.NullUUID         `json:"tenant_id"`
	CreatedAt       sql.NullTime          `json:"created_at"`
	UpdatedAt       sql.NullTime          `json:"updated_at"`
}

// Role-based permissions for table access
type Permission struct {
	ID            uuid.UUID             `json:"id"`
	RoleID        uuid.NullUUID         `json:"role_id"`
	TableName     string                `json:"table_name"`
	Action        string                `json:"action"`
	FieldFilter   pqtype.NullRawMessage `json:"field_filter"`
	AllowedFields []string              `json:"allowed_fields"`
	TenantID      uuid.NullUUID         `json:"tenant_id"`
	CreatedAt     sql.NullTime          `json:"created_at"`
	UpdatedAt     sql.NullTime          `json:"updated_at"`
}

// Role definitions with tenant isolation
type Role struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	TenantID    uuid.NullUUID  `json:"tenant_id"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

// Multi-tenant support - each tenant has isolated data
type Tenant struct {
	ID        uuid.UUID             `json:"id"`
	Name      string                `json:"name"`
	Slug      string                `json:"slug"`
	Domain    sql.NullString        `json:"domain"`
	Settings  pqtype.NullRawMessage `json:"settings"`
	IsActive  sql.NullBool          `json:"is_active"`
	CreatedAt sql.NullTime          `json:"created_at"`
	UpdatedAt sql.NullTime          `json:"updated_at"`
}

// User accounts with tenant isolation
type User struct {
	ID           uuid.UUID      `json:"id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	IsActive     sql.NullBool   `json:"is_active"`
	TenantID     uuid.NullUUID  `json:"tenant_id"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type UserRole struct {
	UserID    uuid.UUID    `json:"user_id"`
	RoleID    uuid.UUID    `json:"role_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type UserTenant struct {
	UserID    uuid.UUID     `json:"user_id"`
	TenantID  uuid.UUID     `json:"tenant_id"`
	RoleID    uuid.NullUUID `json:"role_id"`
	IsActive  sql.NullBool  `json:"is_active"`
	CreatedAt sql.NullTime  `json:"created_at"`
}
